# Generated by Django 4.2.7 on 2024-01-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brug',
            name='nahodne_policko',
            field=models.CharField(default='x', max_length=200),
        ),
        migrations.AddField(
            model_name='brug',
            name='title',
            field=models.CharField(default='x', max_length=200),
        ),
    ]
